import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateBairros1687886068944 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "TB_BAIRRO" ("codigoBairro" number GENERATED BY DEFAULT AS IDENTITY, "codigoMunicipio" number NOT NULL, "nome" varchar2(255) NOT NULL, "status" number NOT NULL, "municipioCodigoMunicipio" number, CONSTRAINT "PK_TBBAIRRO" PRIMARY KEY ("codigoBairro"))`,
    );
    await queryRunner.query(
      `ALTER TABLE "TB_BAIRRO" ADD CONSTRAINT "FK_TBBAIRRO" FOREIGN KEY ("municipioCodigoMunicipio") REFERENCES "TB_MUNICIPIO" ("codigoMunicipio") ON DELETE CASCADE`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "TB_BAIRRO" DROP CONSTRAINT "FK_TBBAIRRO"`,
    );
    await queryRunner.query(`DROP TABLE "TB_BAIRRO"`);
  }
}
