import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreatePessoasEEnderecos1687966893686
  implements MigrationInterface
{
  name = 'CreatePessoasEEnderecos1687966893686';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "TB_PESSOA" ("codigoPessoa" number GENERATED BY DEFAULT AS IDENTITY, "nome" varchar2(255) NOT NULL, "sobrenome" varchar2(255) NOT NULL, "idade" number NOT NULL, "login" varchar2(255) NOT NULL, "senha" varchar2(255) NOT NULL, "status" number NOT NULL, CONSTRAINT "UQ_abbafa0bc65aaa3375d3ab2b556" UNIQUE ("login"), CONSTRAINT "PK_515337c88af9d108c2e444a6729" PRIMARY KEY ("codigoPessoa"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "TB_ENDERECO" ("codigoEndereco" number GENERATED BY DEFAULT AS IDENTITY, "codigoPessoa" number NOT NULL, "codigoBairro" number NOT NULL, "nomeRua" varchar2(255) NOT NULL, "numero" varchar2(255) NOT NULL, "complemento" varchar2(255) NOT NULL, "cep" varchar2(255) NOT NULL, "bairroCodigoBairro" number, "pessoaCodigoPessoa" number, CONSTRAINT "PK_b76679f39787127283a5568a25b" PRIMARY KEY ("codigoEndereco"))`,
    );
    await queryRunner.query(
      `ALTER TABLE "TB_ENDERECO" ADD CONSTRAINT "FK_6b0c97be519dd2d76ba5417f543" FOREIGN KEY ("bairroCodigoBairro") REFERENCES "TB_BAIRRO" ("codigoBairro") ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "TB_ENDERECO" ADD CONSTRAINT "FK_30594051b3a8ce6f76ed9a65989" FOREIGN KEY ("pessoaCodigoPessoa") REFERENCES "TB_PESSOA" ("codigoPessoa") ON DELETE CASCADE`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "TB_ENDERECO" DROP CONSTRAINT "FK_30594051b3a8ce6f76ed9a65989"`,
    );
    await queryRunner.query(
      `ALTER TABLE "TB_ENDERECO" DROP CONSTRAINT "FK_6b0c97be519dd2d76ba5417f543"`,
    );
    await queryRunner.query(`DROP TABLE "TB_ENDERECO"`);
    await queryRunner.query(`DROP TABLE "TB_PESSOA"`);
  }
}
