import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateMunicipios1687827919481 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "TB_MUNICIPIO" ("codigoMunicipio" number GENERATED BY DEFAULT AS IDENTITY, "codigoUF" number NOT NULL, "nome" varchar2(255) NOT NULL, "status" number NOT NULL, "ufCodigoUF" number, CONSTRAINT "PK_8060f658695f5edde4224ad8810" PRIMARY KEY ("codigoMunicipio"))`,
    );
    await queryRunner.query(
      `ALTER TABLE "TB_MUNICIPIO" ADD CONSTRAINT "FK_8cf86b8aeee5d719c0c2376fdcf" FOREIGN KEY ("ufCodigoUF") REFERENCES "TB_UF" ("codigoUF") ON DELETE CASCADE`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "TB_MUNICIPIO" DROP CONSTRAINT "FK_8cf86b8aeee5d719c0c2376fdcf"`,
    );
    await queryRunner.query(`DROP TABLE "TB_MUNICIPIO"`);
  }
}
